{% set name = "swmr-tools" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/swmr_tools-{{ version }}.tar.gz
  sha256: 983ab18804c880ff4168d9042b87048462dd00adc1a0ccd18cc1d9b5a85c2735

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - numpy
    - h5py
    - python >=3.6

test:
  imports:
    - swmr_tools
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/DiamondLightSource/python-swmrtools
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python tools for working with HDF5 SWMR files
  doc_url: https://python-swmrtools.readthedocs.io
  dev_url: https://github.com/DiamondLightSource/python-swmrtools

extra:
  recipe-maintainers:
    - PeterC-DLS
    - jacobfilik